// Get todo list
export const GET_LIST_MOVIE = 'GET_LIST_MOVIE'
export const GET_LIST_MOVIE_START = 'GET_LIST_MOVIE_START'
export const GET_LIST_MOVIE_SUCCESS = 'GET_LIST_MOVIE_SUCCESS'
export const GET_LIST_MOVIE_FAILED = 'GET_LIST_MOVIE_FAILED'